//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Questionnaires.Core.BusinessObjects
{
    public partial class Answer 
    {
        #region Primitive Properties
    
        public virtual int AnswerID
        {
            get;
            set;
        }
    
        public virtual int AnswerSetID
        {
            get { return _answerSetID; }
            set
            {
                if (_answerSetID != value)
                {
                    if (AnswerSet != null && AnswerSet.AnswerSetID != value)
                    {
                        AnswerSet = null;
                    }
                    _answerSetID = value;
                }
            }
        }
        private int _answerSetID;
    
        public virtual int QuestionID
        {
            get { return _questionID; }
            set
            {
                if (_questionID != value)
                {
                    if (Question != null && Question.QuestionID != value)
                    {
                        Question = null;
                    }
                    _questionID = value;
                }
            }
        }
        private int _questionID;
    
        public virtual string Value
        {
            get;
            set;
        }
    
        public virtual System.DateTime Date
        {
            get;
            set;
        }
    
        public virtual string OperatorID
        {
            get;
            set;
        }
    
        public virtual string Type
        {
            get;
            set;
        }
    
        public virtual int Page
        {
            get;
            set;
        }
    
        public virtual int Order
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual AnswerSet AnswerSet
        {
            get { return _answerSet; }
            set
            {
                if (!ReferenceEquals(_answerSet, value))
                {
                    var previousValue = _answerSet;
                    _answerSet = value;
                    FixupAnswerSet(previousValue);
                }
            }
        }
        private AnswerSet _answerSet;
    
        public virtual Question Question
        {
            get { return _question; }
            set
            {
                if (!ReferenceEquals(_question, value))
                {
                    var previousValue = _question;
                    _question = value;
                    FixupQuestion(previousValue);
                }
            }
        }
        private Question _question;

        #endregion
        #region Association Fixup
    
        private void FixupAnswerSet(AnswerSet previousValue)
        {
            if (previousValue != null && previousValue.Answers.Contains(this))
            {
                previousValue.Answers.Remove(this);
            }
    
            if (AnswerSet != null)
            {
                if (!AnswerSet.Answers.Contains(this))
                {
                    AnswerSet.Answers.Add(this);
                }
                if (AnswerSetID != AnswerSet.AnswerSetID)
                {
                    AnswerSetID = AnswerSet.AnswerSetID;
                }
            }
        }
    
        private void FixupQuestion(Question previousValue)
        {
            if (previousValue != null && previousValue.Answers.Contains(this))
            {
                previousValue.Answers.Remove(this);
            }
    
            if (Question != null)
            {
                if (!Question.Answers.Contains(this))
                {
                    Question.Answers.Add(this);
                }
                if (QuestionID != Question.QuestionID)
                {
                    QuestionID = Question.QuestionID;
                }
            }
        }

        #endregion
    }
}
