//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Questionnaires.Core.BusinessObjects
{
    public partial class Condition 
    {
        #region Primitive Properties
    
        public virtual int ConditionID
        {
            get;
            set;
        }
    
        public virtual string Label
        {
            get;
            set;
        }
    
        public virtual string OperatorType
        {
            get;
            set;
        }
    
        public virtual string ValueType
        {
            get;
            set;
        }
    
        public virtual string Value1
        {
            get;
            set;
        }
    
        public virtual string Value2
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<AnswerOption> AnswerOptions
        {
            get
            {
                if (_answerOptions == null)
                {
                    var newCollection = new FixupCollection<AnswerOption>();
                    newCollection.CollectionChanged += FixupAnswerOptions;
                    _answerOptions = newCollection;
                }
                return _answerOptions;
            }
            set
            {
                if (!ReferenceEquals(_answerOptions, value))
                {
                    var previousValue = _answerOptions as FixupCollection<AnswerOption>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAnswerOptions;
                    }
                    _answerOptions = value;
                    var newValue = value as FixupCollection<AnswerOption>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAnswerOptions;
                    }
                }
            }
        }
        private ICollection<AnswerOption> _answerOptions;

        #endregion
        #region Association Fixup
    
        private void FixupAnswerOptions(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (AnswerOption item in e.NewItems)
                {
                    item.Condition = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (AnswerOption item in e.OldItems)
                {
                    if (ReferenceEquals(item.Condition, this))
                    {
                        item.Condition = null;
                    }
                }
            }
        }

        #endregion
    }
}
