//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Questionnaires.Core.BusinessObjects
{
    public partial class QuestionSetQuestion 
    {
        #region Primitive Properties
    
        public virtual int QuestionSetQuestionID
        {
            get;
            set;
        }
    
        public virtual int QuestionSetID
        {
            get { return _questionSetID; }
            set
            {
                if (_questionSetID != value)
                {
                    if (QuestionSet != null && QuestionSet.QuestionSetID != value)
                    {
                        QuestionSet = null;
                    }
                    _questionSetID = value;
                }
            }
        }
        private int _questionSetID;
    
        public virtual int QuestionID
        {
            get { return _questionID; }
            set
            {
                if (_questionID != value)
                {
                    if (Question != null && Question.QuestionID != value)
                    {
                        Question = null;
                    }
                    _questionID = value;
                }
            }
        }
        private int _questionID;
    
        public virtual int Page
        {
            get;
            set;
        }
    
        public virtual int Order
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Question Question
        {
            get { return _question; }
            set
            {
                if (!ReferenceEquals(_question, value))
                {
                    var previousValue = _question;
                    _question = value;
                    FixupQuestion(previousValue);
                }
            }
        }
        private Question _question;
    
        public virtual QuestionSet QuestionSet
        {
            get { return _questionSet; }
            set
            {
                if (!ReferenceEquals(_questionSet, value))
                {
                    var previousValue = _questionSet;
                    _questionSet = value;
                    FixupQuestionSet(previousValue);
                }
            }
        }
        private QuestionSet _questionSet;

        #endregion
        #region Association Fixup
    
        private void FixupQuestion(Question previousValue)
        {
            if (previousValue != null && previousValue.QuestionSetQuestions.Contains(this))
            {
                previousValue.QuestionSetQuestions.Remove(this);
            }
    
            if (Question != null)
            {
                if (!Question.QuestionSetQuestions.Contains(this))
                {
                    Question.QuestionSetQuestions.Add(this);
                }
                if (QuestionID != Question.QuestionID)
                {
                    QuestionID = Question.QuestionID;
                }
            }
        }
    
        private void FixupQuestionSet(QuestionSet previousValue)
        {
            if (previousValue != null && previousValue.QuestionSetQuestions.Contains(this))
            {
                previousValue.QuestionSetQuestions.Remove(this);
            }
    
            if (QuestionSet != null)
            {
                if (!QuestionSet.QuestionSetQuestions.Contains(this))
                {
                    QuestionSet.QuestionSetQuestions.Add(this);
                }
                if (QuestionSetID != QuestionSet.QuestionSetID)
                {
                    QuestionSetID = QuestionSet.QuestionSetID;
                }
            }
        }

        #endregion
    }
}
