//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSD.ElephantParade.DocumentGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSD.ElephantParade.DocumentGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c/o Solent NHS Trust.
        /// </summary>
        internal static string HealthlinesAddress1 {
            get {
                return ResourceManager.GetString("HealthlinesAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adelaide Health Centre.
        /// </summary>
        internal static string HealthlinesAddress2 {
            get {
                return ResourceManager.GetString("HealthlinesAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to William Macleod Way, Southampton.
        /// </summary>
        internal static string HealthlinesAddressCounty {
            get {
                return ResourceManager.GetString("HealthlinesAddressCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Healthlines Study.
        /// </summary>
        internal static string HealthlinesAddressName {
            get {
                return ResourceManager.GetString("HealthlinesAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO16 4XE.
        /// </summary>
        internal static string HealthlinesAddressPostcode {
            get {
                return ResourceManager.GetString("HealthlinesAddressPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western Community Hospital Campus.
        /// </summary>
        internal static string HealthlinesAddressTown {
            get {
                return ResourceManager.GetString("HealthlinesAddressTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snhs.healthlines@nhs.net.
        /// </summary>
        internal static string HealthlinesEmail {
            get {
                return ResourceManager.GetString("HealthlinesEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone: 0345 603 0897.
        /// </summary>
        internal static string HealthlinesTelephone {
            get {
                return ResourceManager.GetString("HealthlinesTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Letter_to_GP___Smoking_Cessation___CVD {
            get {
                object obj = ResourceManager.GetObject("Letter_to_GP___Smoking_Cessation___CVD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NICE_treatment_algorithm_for_hypertension {
            get {
                object obj = ResourceManager.GetObject("NICE_treatment_algorithm_for_hypertension", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
