//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSD.ElephantParade.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHSD.ElephantParade.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string Address1LabelText {
            get {
                return ResourceManager.GetString("Address1LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string Address2LabelText {
            get {
                return ResourceManager.GetString("Address2LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        public static string Address3LabelText {
            get {
                return ResourceManager.GetString("Address3LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AddressCountryLabelText {
            get {
                return ResourceManager.GetString("AddressCountryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        public static string AddressCountyLabelText {
            get {
                return ResourceManager.GetString("AddressCountyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string AddressPostalCodeLabelText {
            get {
                return ResourceManager.GetString("AddressPostalCodeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DOB.
        /// </summary>
        public static string DOBInvalid {
            get {
                return ResourceManager.GetString("DOBInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string EducationLabelText {
            get {
                return ResourceManager.GetString("EducationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string EmailAddressInvalid {
            get {
                return ResourceManager.GetString("EmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        public static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The existing email address is invalid.
        /// </summary>
        public static string ExistingEmailAddressInvalid {
            get {
                return ResourceManager.GetString("ExistingEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The existing email address is required.
        /// </summary>
        public static string ExistingEmailAddressRequired {
            get {
                return ResourceManager.GetString("ExistingEmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string GPAddressLabelText {
            get {
                return ResourceManager.GetString("GPAddressLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string GPEmailLabelText {
            get {
                return ResourceManager.GetString("GPEmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GPNameLabelText {
            get {
                return ResourceManager.GetString("GPNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        public static string GPPracticeLabelText {
            get {
                return ResourceManager.GetString("GPPracticeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Care Trust.
        /// </summary>
        public static string GPPrimaryCareTrustLabelText {
            get {
                return ResourceManager.GetString("GPPrimaryCareTrustLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string GPTelephoneLabelText {
            get {
                return ResourceManager.GetString("GPTelephoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose.
        /// </summary>
        public static string MedicationDoseLabelText {
            get {
                return ResourceManager.GetString("MedicationDoseLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose Required.
        /// </summary>
        public static string MedicationDoseRequiredText {
            get {
                return ResourceManager.GetString("MedicationDoseRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string MedicationfrequencyLabelText {
            get {
                return ResourceManager.GetString("MedicationfrequencyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Required.
        /// </summary>
        public static string MedicationfrequencyRequiredText {
            get {
                return ResourceManager.GetString("MedicationfrequencyRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MedicationNameLabelText {
            get {
                return ResourceManager.GetString("MedicationNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MedicationTypeLabelText {
            get {
                return ResourceManager.GetString("MedicationTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Required.
        /// </summary>
        public static string MedicationTypeRequired {
            get {
                return ResourceManager.GetString("MedicationTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string MedicationTypeRequiredText {
            get {
                return ResourceManager.GetString("MedicationTypeRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new email address is invalid.
        /// </summary>
        public static string NewEmailAddressInvalid {
            get {
                return ResourceManager.GetString("NewEmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new email address is required.
        /// </summary>
        public static string NewEmailAddressRequired {
            get {
                return ResourceManager.GetString("NewEmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string ParticipantPostalCodeLabelText {
            get {
                return ResourceManager.GetString("ParticipantPostalCodeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PatientAddressLabelText {
            get {
                return ResourceManager.GetString("PatientAddressLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline GAD7.
        /// </summary>
        public static string PatientBaselineGAD7TypeLabelText {
            get {
                return ResourceManager.GetString("PatientBaselineGAD7TypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline PHQ9.
        /// </summary>
        public static string PatientBaselinePHQ9LabelText {
            get {
                return ResourceManager.GetString("PatientBaselinePHQ9LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PatientDisplayNameLabelText {
            get {
                return ResourceManager.GetString("PatientDisplayNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name Required.
        /// </summary>
        public static string PatientDisplayNameRequired {
            get {
                return ResourceManager.GetString("PatientDisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name length.
        /// </summary>
        public static string PatientDisplayNameStringLengthValidationError {
            get {
                return ResourceManager.GetString("PatientDisplayNameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string PatientDOBLabelText {
            get {
                return ResourceManager.GetString("PatientDOBLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PatientEmailLabelText {
            get {
                return ResourceManager.GetString("PatientEmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity.
        /// </summary>
        public static string PatientEthnicityLabelText {
            get {
                return ResourceManager.GetString("PatientEthnicityLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forename.
        /// </summary>
        public static string PatientForenameLabelText {
            get {
                return ResourceManager.GetString("PatientForenameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forename Required.
        /// </summary>
        public static string PatientForenameRequired {
            get {
                return ResourceManager.GetString("PatientForenameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forename too long.
        /// </summary>
        public static string PatientForenameStringLengthValidationError {
            get {
                return ResourceManager.GetString("PatientForenameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string PatientGenderLabelText {
            get {
                return ResourceManager.GetString("PatientGenderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string PatientMobileLabelText {
            get {
                return ResourceManager.GetString("PatientMobileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number.
        /// </summary>
        public static string PatientNhsNumberLabelText {
            get {
                return ResourceManager.GetString("PatientNhsNumberLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number Required.
        /// </summary>
        public static string PatientNhsNumberRequired {
            get {
                return ResourceManager.GetString("PatientNhsNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Validation Error.
        /// </summary>
        public static string PatientNhsNumberStringLengthValidationError {
            get {
                return ResourceManager.GetString("PatientNhsNumberStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Antidepressants.
        /// </summary>
        public static string PatientOnAntidepressantsTypeLabelText {
            get {
                return ResourceManager.GetString("PatientOnAntidepressantsTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred contact time.
        /// </summary>
        public static string PatientPrederredContactTimeLabelText {
            get {
                return ResourceManager.GetString("PatientPrederredContactTimeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Contact Number.
        /// </summary>
        public static string PatientPreferredContactNumberTypeLabelText {
            get {
                return ResourceManager.GetString("PatientPreferredContactNumberTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Date.
        /// </summary>
        public static string PatientRegisteredDateLabelText {
            get {
                return ResourceManager.GetString("PatientRegisteredDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PatientStatusLabelText {
            get {
                return ResourceManager.GetString("PatientStatusLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string PatientSurnameLabelText {
            get {
                return ResourceManager.GetString("PatientSurnameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname Required.
        /// </summary>
        public static string PatientSurnameRequired {
            get {
                return ResourceManager.GetString("PatientSurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname too long.
        /// </summary>
        public static string PatientSurnameStringLengthValidationError {
            get {
                return ResourceManager.GetString("PatientSurnameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string PatientTelephoneLabelText {
            get {
                return ResourceManager.GetString("PatientTelephoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string PatientTelephoneNumberMobileLabelText {
            get {
                return ResourceManager.GetString("PatientTelephoneNumberMobileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Number.
        /// </summary>
        public static string PatientTelephoneNumberOtherLabelText {
            get {
                return ResourceManager.GetString("PatientTelephoneNumberOtherLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PatientTitleLabelText {
            get {
                return ResourceManager.GetString("PatientTitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Required.
        /// </summary>
        public static string PatientTitleRequired {
            get {
                return ResourceManager.GetString("PatientTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title too long.
        /// </summary>
        public static string PatientTitleStringLengthValidationError {
            get {
                return ResourceManager.GetString("PatientTitleStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode too long.
        /// </summary>
        public static string PostalCodeStringLengthValidationError {
            get {
                return ResourceManager.GetString("PostalCodeStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consented.
        /// </summary>
        public static string StudyConsentedDateLabelText {
            get {
                return ResourceManager.GetString("StudyConsentedDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudyID Required.
        /// </summary>
        public static string StudyIdRequired {
            get {
                return ResourceManager.GetString("StudyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Referred.
        /// </summary>
        public static string StudyReferralDateLabelText {
            get {
                return ResourceManager.GetString("StudyReferralDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string StudySiteLabelText {
            get {
                return ResourceManager.GetString("StudySiteLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrialID.
        /// </summary>
        public static string StudyTrialNumberLabelText {
            get {
                return ResourceManager.GetString("StudyTrialNumberLabelText", resourceCulture);
            }
        }
    }
}
